# Generated by Django 4.1.3 on 2022-12-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oproducto', models.CharField(max_length=50)),
                ('onombre', models.CharField(max_length=50)),
                ('omarca', models.CharField(max_length=50)),
                ('oprecio_oferta', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('altura', models.IntegerField()),
            ],
        ),
    ]
